name       : broot
version    : 1.16.1
release    : 16
source     :
    - https://github.com/Canop/broot/archive/refs/tags/v1.16.1.tar.gz : 1eb13f2ff6acb781886a742be43ed5e421fd36eed981806e136bbc8eb63fa63a
homepage   : https://dystroy.org/broot/
license    : MIT
component  : system.utils
summary    : A new way to see and navigate directory trees
description: |
    A new way to see and navigate directory trees using cd, tree, and fuzzy search.
networking : yes
builddeps  :
    - cargo
build      : |
    cargo build --release
install    : |
    install -Dm00755 target/release/broot $installdir/usr/bin/broot

    # install manpage
    sed -i "s/#date//" man/page
    sed -i "s/#version/%version%/" man/page
    install -Dm00644 man/page $installdir/usr/share/man/man1/broot.1
