name       : broot
version    : 1.6.3
release    : 8
source     :
    - https://github.com/Canop/broot/archive/refs/tags/v1.6.3.tar.gz : c7ef696a9da162a4338790a9e021eddedcc9a5be321bfea5cc2c33b2b2a53472
license    : MIT
component  : system.utils
summary    : A new way to see and navigate directory trees
description: |
    A new way to see and navigate directory trees using cd, tree, and fuzzy search.
networking : yes
builddeps  :
    - cargo
build      : |
    cargo build --release
install    : |
    install -Dm00755 $workdir/target/release/broot $installdir/usr/bin/broot
