name       : broot
version    : 1.0.9
release    : 2
source     :
    - https://github.com/Canop/broot/archive/v1.0.9.tar.gz : 66f998d425631673af2772bc4ebafa55f4d74224cbd99bd5570bba53d50be27a
license    : MIT
component  : system.utils
summary    : A new way to see and navigate directory trees
description: |
    A new way to see and navigate directory trees using cd, tree, and fuzzy search.
networking : yes
builddeps  :
    - cargo
build      : |
    cargo build --release --locked
install    : |
    install -Dm00755 $workdir/target/release/broot $installdir/usr/bin/broot
