name       : broot
version    : 1.2.0
release    : 4
source     :
    - https://github.com/Canop/broot/archive/v1.2.0.tar.gz : 87758fd6bc4bc3db32d6a557b84db28fa527be2102ecf9c465cb5a0393af428f
license    : MIT
component  : system.utils
summary    : A new way to see and navigate directory trees
description: |
    A new way to see and navigate directory trees using cd, tree, and fuzzy search.
networking : yes
builddeps  :
    - cargo
build      : |
    cargo build --release --locked
install    : |
    install -Dm00755 $workdir/target/release/broot $installdir/usr/bin/broot
