name       : broot
version    : 1.24.2
release    : 19
source     :
    - https://github.com/Canop/broot/archive/refs/tags/v1.24.2.tar.gz : cf223710bd75362d37312ef50b4966d57a79b36e3e645f940fd34569075f3974
homepage   : https://dystroy.org/broot/
license    : MIT
component  : system.utils
summary    : A new way to see and navigate directory trees
description: |
    A new way to see and navigate directory trees using cd, tree, and fuzzy search.
networking : yes
builddeps  :
    - cargo
build      : |
    cargo build --release
install    : |
    install -Dm00755 target/release/broot $installdir/usr/bin/broot

    # install manpage
    sed -i "s/#date//" man/page
    sed -i "s/#version/%version%/" man/page
    install -Dm00644 resources/icons/vscode/vscode.ttf $installdir/usr/share/fonts/truetype/vscode.ttf
    install -Dm00644 man/page $installdir/usr/share/man/man1/broot.1
