name       : broot
version    : 1.1.10
release    : 3
source     :
    - https://github.com/Canop/broot/archive/v1.1.10.tar.gz : f40e63cf8bcf7d70a42d528696fe0355ff5a4a80cfd654593dabdd866613bc60
license    : MIT
component  : system.utils
summary    : A new way to see and navigate directory trees
description: |
    A new way to see and navigate directory trees using cd, tree, and fuzzy search.
networking : yes
builddeps  :
    - cargo
build      : |
    cargo build --release --locked
install    : |
    install -Dm00755 $workdir/target/release/broot $installdir/usr/bin/broot
