name       : broot
version    : 1.19.0
release    : 17
source     :
    - https://github.com/Canop/broot/archive/refs/tags/v1.19.0.tar.gz : 3345bd0eb17f954212bd12528c476acaa0e4dacb38ad78a047b5aedc2f638c15
homepage   : https://dystroy.org/broot/
license    : MIT
component  : system.utils
summary    : A new way to see and navigate directory trees
description: |
    A new way to see and navigate directory trees using cd, tree, and fuzzy search.
networking : yes
builddeps  :
    - cargo
build      : |
    cargo build --release
install    : |
    install -Dm00755 target/release/broot $installdir/usr/bin/broot

    # install manpage
    sed -i "s/#date//" man/page
    sed -i "s/#version/%version%/" man/page
    install -Dm00644 man/page $installdir/usr/share/man/man1/broot.1
