name       : broot
version    : 1.2.2
release    : 6
source     :
    - https://github.com/Canop/broot/archive/v1.2.2.tar.gz : ff939cec1b7ff3eadae74f9242cf4a093e1fb40a717fc921c6340f4f2081f1a3
license    : MIT
component  : system.utils
summary    : A new way to see and navigate directory trees
description: |
    A new way to see and navigate directory trees using cd, tree, and fuzzy search.
networking : yes
builddeps  :
    - cargo
build      : |
    cargo build --release
install    : |
    install -Dm00755 $workdir/target/release/broot $installdir/usr/bin/broot
