name       : broot
version    : 1.12.0
release    : 12
source     :
    - https://github.com/Canop/broot/archive/refs/tags/v1.12.0.tar.gz : 94b5bc7fa79f379c2c23c23402e7a076495b4d23ca7d89e4631702dbff15fb82
homepage   : https://dystroy.org/broot/
license    : MIT
component  : system.utils
summary    : A new way to see and navigate directory trees
description: |
    A new way to see and navigate directory trees using cd, tree, and fuzzy search.
networking : yes
builddeps  :
    - cargo
build      : |
    cargo build --release
install    : |
    install -Dm00755 target/release/broot $installdir/usr/bin/broot

    # install manpage
    sed -i "s/#date//" man/page
    sed -i "s/#version/%version%/" man/page
    install -Dm00644 man/page $installdir/usr/share/man/man1/broot.1
