name       : broot
version    : 1.6.1
release    : 7
source     :
    - https://github.com/Canop/broot/archive/refs/tags/v1.6.1.tar.gz : 5f97d876aa554be4c67bfd161ef762425f6083da583775c13cc75bf9882f1085
license    : MIT
component  : system.utils
summary    : A new way to see and navigate directory trees
description: |
    A new way to see and navigate directory trees using cd, tree, and fuzzy search.
networking : yes
builddeps  :
    - cargo
build      : |
    cargo build --release
install    : |
    install -Dm00755 $workdir/target/release/broot $installdir/usr/bin/broot
