name       : broot
version    : 0.13.6
release    : 1
source     :
    - https://github.com/Canop/broot/archive/v0.13.6.tar.gz : f28eea78bba1660ecdbdb9ebac8e215b7523b94f7d490d69d8022df44eacec3c
license    : MIT
component  : system.utils
summary    : A new way to see and navigate directory trees
description: |
    A new way to see and navigate directory trees using cd, tree, and fuzzy search.
networking : yes
builddeps  : 
    cargo
build      : |
    cargo build --release --locked
install    : |
    install -Dm00755 $workdir/target/release/broot $installdir/usr/bin/broot
    # install -Dm00644 $workdir/target/release/build/broot-440f2c71a02ef3c5/out/_* -t $installdir/usr/share/zsh/site-functions/
    # install -Dm00644 $workdir/target/release/build/broot-440f2c71a02ef3c5/out/*.fish -t $installdir/usr/share/fish/completions/
    # install -Dm00644 $workdir/target/release/build/broot-440f2c71a02ef3c5/out/*.bash -t $installdir/usr/share/bash-completion/completions/
    # install -Dm00644 $workdir/man/page $installdir/usr/share/man/man1/broot.1
    find . -name _* -exec install -Dm00644 '{}' -t "$installdir/usr/share/zsh/site-functions/" ";"
    find . -name *.bash -exec install -Dm00644 '{}' -t "$installdir/usr/share/bash-completion/completions/" ";"
    find . -name *.fish -exec install -Dm00644 '{}' -t "$installdir/usr/share/fish/completions/" ";"
